'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {planInitialAssignment,planAssignmentReplacement}=require('../platform/assignments/assignment-persistence-plan');
const auth=require('../platform/core/authorization-decision-service');

const actor=(role,uid=`${role}-a`,organizationId='org-a')=>({role,uid,organizationId});
const observation=(overrides={})=>({id:'obs-a',organizationId:'org-a',createdByUid:'inspector-a',status:'PENDING',...overrides});
const assignment=(overrides={})=>({assignmentId:'a-1',organizationId:'org-a',observationId:'obs-a',contractorId:'contractor-a',status:'ACTIVE',version:1,assignedAt:'t1',assignedBy:'manager-a',createdAt:'t1',updatedAt:'t1',...overrides});

test('initial assignment plan creates assignment and pointer atomically',()=>{const r=planInitialAssignment({observation:observation(),assignment:assignment()});assert.equal(r.decision.allowed,true);assert.equal(r.operations.length,2);assert.deepEqual(r.operations.map(x=>x.type),['create','update']);});
test('initial assignment plan rejects second current assignment',()=>{const r=planInitialAssignment({observation:observation({currentAssignmentId:'old'}),assignment:assignment()});assert.equal(r.decision.allowed,false);assert.equal(r.decision.code,'INITIAL_ASSIGNMENT_INVARIANT_FAILED');});
test('replacement plan advances exactly one version in three atomic operations',()=>{const current=assignment(),next=assignment({assignmentId:'a-2',contractorId:'contractor-b',version:2,assignedAt:'t2',createdAt:'t2',updatedAt:'t2'});const r=planAssignmentReplacement({observation:observation({currentAssignmentId:'a-1',currentAssignmentVersion:1}),currentAssignment:current,nextAssignment:next,endedAt:'t2'});assert.equal(r.decision.allowed,true);assert.equal(r.operations.length,3);assert.equal(r.operations[0].data.status,'REPLACED');assert.equal(r.operations[2].data.currentAssignmentId,'a-2');});
test('replacement plan rejects stale or skipped version',()=>{const current=assignment(),next=assignment({assignmentId:'a-2',version:3});const r=planAssignmentReplacement({observation:observation({currentAssignmentId:'a-1',currentAssignmentVersion:1}),currentAssignment:current,nextAssignment:next,endedAt:'t2'});assert.equal(r.decision.allowed,false);assert.equal(r.decision.code,'REPLACEMENT_INVARIANT_FAILED');});

test('policy parity contractor own ACTIVE start is ALLOW',()=>{const r=auth.canStartObservation({actor:actor('contractor'),observation:observation({currentAssignmentId:'a-1',currentAssignmentVersion:1}),assignment:assignment()});assert.equal(r.allowed,true);});
test('policy parity contractor wrong assignment is DENY',()=>{const r=auth.canStartObservation({actor:actor('contractor'),observation:observation({currentAssignmentId:'a-1',currentAssignmentVersion:1}),assignment:assignment({contractorId:'contractor-b'})});assert.equal(r.allowed,false);});
test('policy parity contractor submit own evidence is ALLOW',()=>{const r=auth.canSubmitEvidence({actor:actor('contractor'),observation:observation({status:'IN_PROGRESS',currentAssignmentId:'a-1',currentAssignmentVersion:1}),assignment:assignment()});assert.equal(r.allowed,true);});
test('policy parity inspector other-owner and completion are DENY',()=>{assert.equal(auth.canUpdateObservation({actor:actor('inspector'),observation:observation({createdByUid:'inspector-b'})}).allowed,false);assert.equal(auth.canCompleteObservation({actor:actor('inspector'),observation:observation({status:'PENDING_REVIEW'})}).allowed,false);});
test('policy parity manager completes review and returns review',()=>{const ctx={actor:actor('manager'),observation:observation({status:'PENDING_REVIEW'})};assert.equal(auth.canCompleteObservation(ctx).allowed,true);assert.equal(auth.canReturnObservation(ctx).allowed,true);});
test('policy parity supervisor returns but cannot complete',()=>{const ctx={actor:actor('supervisor'),observation:observation({status:'PENDING_REVIEW'})};assert.equal(auth.canReturnObservation(ctx).allowed,true);assert.equal(auth.canCompleteObservation(ctx).allowed,false);});
test('policy parity COMPLETED is terminal',()=>{for(const role of ['manager','supervisor','inspector','contractor'])assert.equal(auth.canReturnObservation({actor:actor(role),observation:observation({status:'COMPLETED'}),assignment:role==='contractor'?assignment():undefined}).allowed,false);});
