'use strict';
const {before,after,beforeEach,test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {pathToFileURL}=require('node:url');
const {initializeTestEnvironment}=require('@firebase/rules-unit-testing');const sdk=require('firebase/firestore');
const {createFeatureFlags,PLATFORM_ASSIGNMENT_V2}=require('../platform/config/feature-flags');const {createAssignmentV2Gateway}=require('../platform/integration/assignment-v2-gateway');const {createCanonicalAssignmentWriteService}=require('../platform/assignments/canonical-assignment-write-service');const {createFirestoreAssignmentStore}=require('../platform/assignments/firestore-assignment-store');
const PROJECT_ID='demo-smart-hsr-phase1e';const manager={uid:'manager-a',role:'manager',organizationId:'org-a'},contractorA={id:'contractor-a',role:'contractor',active:true,organizationId:'org-a'},contractorB={...contractorA,id:'contractor-b'},base={id:'obs-a',organizationId:'org-a',createdByUid:'inspector-a',status:'PENDING'};let env,callsite;
const override={environment:'preview',projectId:PROJECT_ID,flags:{PLATFORM_ASSIGNMENT_V2:true}};
before(async()=>{callsite=await import(pathToFileURL(path.resolve(__dirname,'../platform/integration/manager-assignment-preview.mjs')).href);env=await initializeTestEnvironment({projectId:PROJECT_ID,firestore:{rules:fs.readFileSync(path.resolve(__dirname,'..','firestore.rules.phase-1c-candidate'),'utf8'),host:'127.0.0.1',port:8080}});});after(async()=>{if(env)await env.cleanup();});beforeEach(async()=>{await env.clearFirestore();await env.withSecurityRulesDisabled(async c=>{const db=c.firestore();await sdk.setDoc(sdk.doc(db,'managers',manager.uid),{role:'manager',active:true,organizationId:'org-a'});await sdk.setDoc(sdk.doc(db,'observations','obs-a'),base);});});
function gateway(){const db=env.authenticatedContext(manager.uid).firestore(),service=createCanonicalAssignmentWriteService({store:createFirestoreAssignmentStore({db,sdk}),idFactory:()=> 'generated',clock:()=> '2026-08-06T00:00:00.000Z'});return createAssignmentV2Gateway({flags:createFeatureFlags({[PLATFORM_ASSIGNMENT_V2]:true}),assignmentService:service,legacyHandlers:{}});}
async function read(c,id){let v;await env.withSecurityRulesDisabled(async x=>{v=(await sdk.getDoc(sdk.doc(x.firestore(),c,id))).data();});return v;}
const input=(observation,contractor,assignmentId)=>({actor:manager,observation,contractorId:contractor.id,contractor,assignmentId});
test('Preview manager call site creates through gateway against candidate rules',async()=>{let legacy=0;const out=await callsite.executeManagerAssignmentCallsite({override,hostname:'localhost',gateway:gateway(),legacyWrite:async()=>legacy++,input:input(base,contractorA,'a-1')});assert.equal(out.allowed,true);assert.equal(legacy,0);assert.equal((await read('observations','obs-a')).currentAssignmentId,'a-1');});
test('Preview manager call site replaces atomically against candidate rules',async()=>{const g=gateway();await callsite.executeManagerAssignmentCallsite({override,hostname:'localhost',gateway:g,legacyWrite:async()=>assert.fail(),input:input(base,contractorA,'a-1')});const current={id:'obs-a',...await read('observations','obs-a')};const out=await callsite.executeManagerAssignmentCallsite({override,hostname:'localhost',gateway:g,legacyWrite:async()=>assert.fail(),input:input(current,contractorB,'a-2')});assert.equal(out.allowed,true);assert.equal((await read('assignments','a-1')).status,'REPLACED');assert.equal((await read('assignments','a-2')).version,2);});
test('V2 denial never falls back to legacy against candidate rules',async()=>{let legacy=0;const invalid={...base,organizationId:'org-b'};const out=await callsite.executeManagerAssignmentCallsite({override,hostname:'localhost',gateway:gateway(),legacyWrite:async()=>legacy++,input:input(invalid,{...contractorA,organizationId:'org-b'},'a-1')});assert.equal(out.allowed,false);assert.equal(legacy,0);assert.equal(await read('assignments','a-1'),undefined);});
