'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const { DEFAULT_FLAGS, PLATFORM_ASSIGNMENT_V2, createFeatureFlags } = require('../platform/config/feature-flags');
const { BRIDGE_CLASSIFICATIONS, resolveAssignmentBridge } = require('../platform/assignments/legacy-assignment-bridge');
const { createCanonicalAssignmentWriteService } = require('../platform/assignments/canonical-assignment-write-service');
const { createAssignmentV2Gateway } = require('../platform/integration/assignment-v2-gateway');
const { ACTIONS, buildAssignmentAuditEvent } = require('../platform/audit/assignment-audit-events');

const actor = (role='manager', uid='manager-a', organizationId='org-a') => ({ role, uid, organizationId });
const observation = (overrides={}) => ({ id:'obs-a', organizationId:'org-a', createdByUid:'inspector-a', status:'PENDING', ...overrides });
const assignment = (overrides={}) => ({ assignmentId:'a-1', observationId:'obs-a', organizationId:'org-a', contractorId:'contractor-a', status:'ACTIVE', version:1, assignedAt:'t1', assignedBy:'manager-a', createdAt:'t1', updatedAt:'t1', ...overrides });

function memoryStore(initialObservation=observation(), initialAssignments=[]) {
  const state={observations:new Map([[initialObservation.id, structuredClone(initialObservation)]]),assignments:new Map(initialAssignments.map(x=>[x.assignmentId,structuredClone(x)]))};
  const snapshot=()=>structuredClone({observations:[...state.observations],assignments:[...state.assignments]});
  return { state, getAssignment:async id=>structuredClone(state.assignments.get(id)||null), async runTransaction(work){const before=snapshot();const tx={getObservation:async id=>structuredClone(state.observations.get(id)||null),getAssignment:async id=>structuredClone(state.assignments.get(id)||null),createAssignment:async x=>{if(state.assignments.has(x.assignmentId))throw Error('exists');state.assignments.set(x.assignmentId,structuredClone(x));},updateAssignment:async(id,p)=>Object.assign(state.assignments.get(id),structuredClone(p)),updateObservation:async(id,p)=>Object.assign(state.observations.get(id),structuredClone(p))};try{return await work(tx);}catch(error){state.observations=new Map(before.observations);state.assignments=new Map(before.assignments);throw error;}}};
}

test('PLATFORM_ASSIGNMENT_V2 is disabled by default and has deterministic test override',()=>{assert.equal(DEFAULT_FLAGS[PLATFORM_ASSIGNMENT_V2],false);assert.equal(createFeatureFlags().isEnabled(PLATFORM_ASSIGNMENT_V2),false);assert.equal(createFeatureFlags({[PLATFORM_ASSIGNMENT_V2]:true}).isEnabled(PLATFORM_ASSIGNMENT_V2),true);});
test('legacy mode delegates unchanged to existing handler',async()=>{const expected={legacy:true};const gateway=createAssignmentV2Gateway({flags:createFeatureFlags(),assignmentService:{},legacyHandlers:{startExecution:async()=>expected}});assert.equal(await gateway.startExecution({}),expected);});
test('bridge classifies canonical, legacy-compatible, ambiguous, and invalid',()=>{assert.equal(resolveAssignmentBridge({observation:observation({currentAssignmentId:'a-1',currentAssignmentVersion:1}),assignment:assignment()}).classification,BRIDGE_CLASSIFICATIONS.CANONICAL);assert.equal(resolveAssignmentBridge({observation:observation({assignedContractorUid:'c',assignedByUid:'m',assignedAt:'t'})}).classification,BRIDGE_CLASSIFICATIONS.LEGACY_COMPATIBLE);assert.equal(resolveAssignmentBridge({observation:observation({assignedContractorUid:'c'})}).classification,BRIDGE_CLASSIFICATIONS.AMBIGUOUS);assert.equal(resolveAssignmentBridge({observation:{}}).classification,BRIDGE_CLASSIFICATIONS.INVALID);});
test('V2 contractor action fails closed for ambiguous legacy assignment',async()=>{const gateway=createAssignmentV2Gateway({flags:createFeatureFlags({[PLATFORM_ASSIGNMENT_V2]:true}),assignmentService:{},legacyHandlers:{}});const out=await gateway.startExecution({actor:actor('contractor','contractor-a'),observation:observation({assignedContractorUid:'contractor-a'}),patch:{status:'IN_PROGRESS'}});assert.equal(out.allowed,false);assert.equal(out.code,'V2_CANONICAL_ASSIGNMENT_REQUIRED');});
test('createAssignment atomically creates canonical assignment and pointer',async()=>{const store=memoryStore();let id=0;const service=createCanonicalAssignmentWriteService({store,idFactory:()=>`a-${++id}`,clock:()=> 't2'});const out=await service.createAssignment({actor:actor(),observation:observation(),contractorId:'contractor-a'});assert.equal(out.allowed,true);assert.equal(store.state.assignments.size,1);assert.equal(store.state.observations.get('obs-a').currentAssignmentId,'a-1');assert.equal(out.auditEvent.action,ACTIONS.CREATED);});
test('second ACTIVE assignment is denied',async()=>{const obs=observation({currentAssignmentId:'a-1',currentAssignmentVersion:1});const store=memoryStore(obs,[assignment()]);const service=createCanonicalAssignmentWriteService({store,idFactory:()=> 'a-2',clock:()=> 't2'});const out=await service.createAssignment({actor:actor(),observation:obs,contractorId:'contractor-b'});assert.equal(out.allowed,false);assert.equal(store.state.assignments.size,1);});
test('replacement is atomic, increments version, and replaces prior assignment',async()=>{const obs=observation({currentAssignmentId:'a-1',currentAssignmentVersion:1});const store=memoryStore(obs,[assignment()]);const service=createCanonicalAssignmentWriteService({store,idFactory:()=> 'a-2',clock:()=> 't2'});const out=await service.replaceAssignment({actor:actor(),observation:obs,contractorId:'contractor-b'});assert.equal(out.allowed,true);assert.equal(store.state.assignments.get('a-1').status,'REPLACED');assert.equal(store.state.assignments.get('a-1').replacedByAssignmentId,'a-2');assert.equal(store.state.assignments.get('a-2').version,2);assert.equal(store.state.observations.get('obs-a').currentAssignmentId,'a-2');assert.equal([...store.state.assignments.values()].filter(x=>x.status==='ACTIVE').length,1);});
test('endAssignment marks current assignment INACTIVE and clears pointer',async()=>{const obs=observation({currentAssignmentId:'a-1',currentAssignmentVersion:1});const store=memoryStore(obs,[assignment()]);const service=createCanonicalAssignmentWriteService({store,idFactory:()=> 'x',clock:()=> 't2'});const out=await service.endAssignment({actor:actor(),observation:obs});assert.equal(out.allowed,true);assert.equal(store.state.assignments.get('a-1').status,'INACTIVE');assert.equal(store.state.observations.get('obs-a').currentAssignmentId,null);assert.equal(out.auditEvent.action,ACTIONS.ENDED);});
test('cross-organization assignment write is denied before transaction mutation',async()=>{const store=memoryStore();const service=createCanonicalAssignmentWriteService({store,idFactory:()=> 'a-1'});const out=await service.createAssignment({actor:actor('manager','manager-b','org-b'),observation:observation(),contractorId:'c'});assert.equal(out.allowed,false);assert.equal(store.state.assignments.size,0);});
test('V2 valid contractor transition returns a write request but does not execute UI write',async()=>{const obs=observation({currentAssignmentId:'a-1',currentAssignmentVersion:1});const gateway=createAssignmentV2Gateway({flags:createFeatureFlags({[PLATFORM_ASSIGNMENT_V2]:true}),assignmentService:{},legacyHandlers:{},idFactory:()=> '1',clock:()=> 't2'});const out=await gateway.startExecution({actor:actor('contractor','contractor-a'),observation:obs,assignment:assignment(),patch:{status:'IN_PROGRESS'},toStatus:'IN_PROGRESS'});assert.equal(out.allowed,true);assert.deepEqual(out.writeRequest,{observationId:'obs-a',patch:{status:'IN_PROGRESS'}});assert.equal(out.auditEvent.action,ACTIONS.TRANSITION);});
test('V2 denies wrong contractor, stale/replaced assignment, contractor completion, and COMPLETED reopening',async()=>{const flags=createFeatureFlags({[PLATFORM_ASSIGNMENT_V2]:true});const gateway=createAssignmentV2Gateway({flags,assignmentService:{},legacyHandlers:{},idFactory:()=> '1',clock:()=> 't2'});const obs=observation({currentAssignmentId:'a-1',currentAssignmentVersion:1});for(const bad of [assignment({contractorId:'other'}),assignment({version:2}),assignment({status:'REPLACED',endedAt:'t2',replacedByAssignmentId:'a-2'})])assert.equal((await gateway.startExecution({actor:actor('contractor','contractor-a'),observation:obs,assignment:bad,toStatus:'IN_PROGRESS'})).allowed,false);assert.equal((await gateway.completeObservation({actor:actor('contractor','contractor-a'),observation:observation({status:'PENDING_REVIEW',currentAssignmentId:'a-1',currentAssignmentVersion:1}),assignment:assignment(),toStatus:'COMPLETED'})).allowed,false);assert.equal((await gateway.returnObservation({actor:actor(),observation:observation({status:'COMPLETED'}),toStatus:'IN_PROGRESS'})).allowed,false);});
test('inspector cannot update another inspector observation',async()=>{const gateway=createAssignmentV2Gateway({flags:createFeatureFlags({[PLATFORM_ASSIGNMENT_V2]:true}),assignmentService:{},legacyHandlers:{},idFactory:()=> '1',clock:()=> 't2'});const out=await gateway.updateInspectorObservation({actor:actor('inspector','inspector-a'),observation:observation({createdByUid:'inspector-b'}),patch:{resolutionNote:'x'}});assert.equal(out.allowed,false);});
test('audit contract generates created, replaced, ended, denied and transition payloads',()=>{for(const action of Object.values(ACTIONS)){const out=buildAssignmentAuditEvent({action,actor:actor(),observation:observation(),assignmentId:'a-1',decision:{allowed:action!==ACTIONS.DENIED,code:'CHECK'},timestamp:'t2',eventId:`e-${action}`,requestedState:'IN_PROGRESS'});assert.equal(out.decision.allowed,true);assert.equal(out.event.action,action);}});
