'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {pathToFileURL}=require('node:url');const path=require('node:path');
const {createFeatureFlags,PLATFORM_ASSIGNMENT_V2}=require('../platform/config/feature-flags');
const {createAssignmentV2Gateway}=require('../platform/integration/assignment-v2-gateway');
const {createCanonicalAssignmentWriteService}=require('../platform/assignments/canonical-assignment-write-service');
const {resolveAssignmentBridge,BRIDGE_CLASSIFICATIONS}=require('../platform/assignments/legacy-assignment-bridge');
let callsite;
const actor=(role='manager',organizationId='org-a')=>({uid:`${role}-a`,role,organizationId});
const contractor=(overrides={})=>({id:'contractor-a',role:'contractor',active:true,organizationId:'org-a',...overrides});
const observation=(overrides={})=>({id:'obs-a',organizationId:'org-a',createdByUid:'inspector-a',status:'PENDING',...overrides});
const assignment=(overrides={})=>({assignmentId:'a-1',observationId:'obs-a',organizationId:'org-a',contractorId:'contractor-a',status:'ACTIVE',version:1,assignedAt:'t1',assignedBy:'manager-a',createdAt:'t1',updatedAt:'t1',...overrides});
const override={environment:'preview',projectId:'demo-smart-hsr-phase1e',flags:{PLATFORM_ASSIGNMENT_V2:true}};

test.before(async()=>{callsite=await import(pathToFileURL(path.resolve(__dirname,'../platform/integration/manager-assignment-preview.mjs')).href);});
function memoryStore(obs=observation(),assignments=[]){const state={observation:structuredClone(obs),assignments:new Map(assignments.map(x=>[x.assignmentId,structuredClone(x)]))};return{state,getAssignment:async id=>state.assignments.get(id)||null,runTransaction:async work=>work({getObservation:async()=>structuredClone(state.observation),getAssignment:async id=>structuredClone(state.assignments.get(id)||null),createAssignment:async x=>state.assignments.set(x.assignmentId,structuredClone(x)),updateAssignment:async(id,p)=>Object.assign(state.assignments.get(id),structuredClone(p)),updateObservation:async(_id,p)=>Object.assign(state.observation,structuredClone(p))})};}
function v2(store){let seq=1;const service=createCanonicalAssignmentWriteService({store,idFactory:()=>`generated-${seq++}`,clock:()=> 't2'});return createAssignmentV2Gateway({flags:createFeatureFlags({[PLATFORM_ASSIGNMENT_V2]:true}),assignmentService:service,legacyHandlers:{}});}
const input=(overrides={})=>({actor:actor(),observation:observation(),contractorId:'contractor-a',contractor:contractor(),...overrides});

test('legacy creation and replacement execute the unchanged legacy callback',async()=>{let calls=0;const legacyWrite=async value=>{calls++;return{allowed:true,legacy:true,value}};for(const obs of [observation(),observation({assignedContractorUid:'old'})]){const out=await callsite.executeManagerAssignmentCallsite({override:undefined,hostname:'localhost',legacyWrite,input:input({observation:obs})});assert.equal(out.legacy,true);}assert.equal(calls,2);});
test('Preview activation requires explicit preview, demo project, enabled flag and safe host',()=>{assert.equal(callsite.isPreviewAssignmentV2Enabled({override,hostname:'localhost'}),true);for(const bad of [{...override,environment:'production'},{...override,projectId:'smart-hsr-manager'},{...override,flags:{PLATFORM_ASSIGNMENT_V2:false}}])assert.equal(callsite.isPreviewAssignmentV2Enabled({override:bad,hostname:'localhost'}),false);assert.equal(callsite.isPreviewAssignmentV2Enabled({override,hostname:'app.example.com'}),false);});
test('V2 valid creation succeeds without legacy write',async()=>{const store=memoryStore();let legacy=0;const out=await callsite.executeManagerAssignmentCallsite({override,hostname:'localhost',gateway:v2(store),legacyWrite:async()=>{legacy++;},input:input()});assert.equal(out.allowed,true);assert.equal(legacy,0);assert.equal(store.state.assignments.size,1);});
test('V2 replacement replaces previous, increments version and retains one ACTIVE',async()=>{const obs=observation({currentAssignmentId:'a-1',currentAssignmentVersion:1,assignedContractorUid:'contractor-a'}),store=memoryStore(obs,[assignment()]);const out=await callsite.executeManagerAssignmentCallsite({override,hostname:'preview-smart-hsr',gateway:v2(store),legacyWrite:async()=>assert.fail(),input:input({observation:obs,contractorId:'contractor-b',contractor:contractor({id:'contractor-b'})})});assert.equal(out.allowed,true);assert.equal(store.state.assignments.get('a-1').status,'REPLACED');assert.equal([...store.state.assignments.values()].filter(x=>x.status==='ACTIVE').length,1);assert.equal(store.state.observation.currentAssignmentVersion,2);});
test('cross-org, invalid contractor, unauthorized actor, completed and duplicate are denied without fallback',async()=>{let legacy=0;const legacyWrite=async()=>{legacy++;};const cases=[input({actor:actor('manager','org-b')}),input({contractor:contractor({active:false})}),input({actor:actor('inspector')}),input({observation:observation({status:'COMPLETED'})})];for(const value of cases){const out=await callsite.executeManagerAssignmentCallsite({override,hostname:'localhost',gateway:v2(memoryStore(value.observation)),legacyWrite,input:value});assert.equal(out.allowed,false);}const obs=observation({currentAssignmentId:'missing',currentAssignmentVersion:1});assert.equal((await callsite.executeManagerAssignmentCallsite({override,hostname:'localhost',gateway:v2(memoryStore(obs)),legacyWrite,input:input({observation:obs})})).allowed,false);assert.equal(legacy,0);});
test('rollback to legacy works by disabling only the flag',async()=>{let legacy=0;const disabled={...override,flags:{PLATFORM_ASSIGNMENT_V2:false}};const out=await callsite.executeManagerAssignmentCallsite({override:disabled,hostname:'localhost',gateway:{createAssignment:async()=>assert.fail()},legacyWrite:async()=>{legacy++;return{allowed:true,legacy:true};},input:input()});assert.equal(out.legacy,true);assert.equal(legacy,1);});
test('fixture compatibility measurement is deterministic: 62.5 percent compatible',()=>{const fixtures=[
  {observation:observation({currentAssignmentId:'a-1',currentAssignmentVersion:1}),assignment:assignment()},
  {observation:observation({id:'obs-b',currentAssignmentId:'a-2',currentAssignmentVersion:1}),assignment:assignment({assignmentId:'a-2',observationId:'obs-b'})},
  {observation:observation()},
  {observation:observation({assignedContractorUid:'c',assignedByUid:'m',assignedAt:'t'})},
  {observation:observation({id:'obs-c',assignedContractorUid:'c',assignedByUid:'m',assignedAt:'t'})},
  {observation:observation({assignedContractorUid:'c'})},
  {observation:{}},
  {observation:observation({id:'obs-d',currentAssignmentId:'bad',currentAssignmentVersion:1}),assignment:assignment({assignmentId:'bad',observationId:'wrong'})},
];const classes=fixtures.map(resolveAssignmentBridge).map(x=>x.classification);const compatible=classes.filter(x=>[BRIDGE_CLASSIFICATIONS.CANONICAL,BRIDGE_CLASSIFICATIONS.LEGACY_COMPATIBLE].includes(x)).length;assert.equal(compatible/fixtures.length*100,62.5);assert.deepEqual(Object.fromEntries(Object.values(BRIDGE_CLASSIFICATIONS).map(x=>[x,classes.filter(y=>y===x).length])),{canonical:2,'legacy-compatible':3,ambiguous:1,invalid:2});});
