'use strict';
const {before,after,beforeEach,test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {pathToFileURL}=require('node:url');
const {initializeTestEnvironment}=require('@firebase/rules-unit-testing');const sdk=require('firebase/firestore');const bootstrap=require('../platform/bootstrap/assignment-v2-preview-bootstrap');
const PROJECT_ID='demo-smart-hsr-phase1f',manager={uid:'manager-a',role:'manager',organizationId:'org-a'},contractorA={id:'contractor-a',role:'contractor',active:true,organizationId:'org-a'},contractorB={...contractorA,id:'contractor-b'},base={id:'obs-a',organizationId:'org-a',createdByUid:'inspector-a',status:'PENDING'};let env,callsite,db;
const callsiteOverride={environment:'preview',explicitOverride:true,projectId:PROJECT_ID,flags:{PLATFORM_ASSIGNMENT_V2:true}};
before(async()=>{callsite=await import(pathToFileURL(path.resolve(__dirname,'../platform/integration/manager-assignment-preview.mjs')).href);env=await initializeTestEnvironment({projectId:PROJECT_ID,firestore:{rules:fs.readFileSync(path.resolve(__dirname,'..','firestore.rules.phase-1c-candidate'),'utf8'),host:'127.0.0.1',port:8080}});});after(async()=>{if(env)await env.cleanup();});beforeEach(async()=>{bootstrap.resetAssignmentV2PreviewForTests();await env.clearFirestore();db=env.authenticatedContext(manager.uid).firestore();await env.withSecurityRulesDisabled(async c=>{const seed=c.firestore();await sdk.setDoc(sdk.doc(seed,'managers',manager.uid),{role:'manager',active:true,organizationId:'org-a'});await sdk.setDoc(sdk.doc(seed,'observations','obs-a'),base);});});
function initialize(){return bootstrap.initializeAssignmentV2Preview({environment:'preview',explicitOverride:true,featureEnabled:true,hostname:'localhost',projectId:PROJECT_ID,emulatorConnected:true,app:db.app,db,sdk,clock:()=> '2026-08-06T00:00:00.000Z',idFactory:()=> 'generated'});}
async function read(c,id){let value;await env.withSecurityRulesDisabled(async x=>{value=(await sdk.getDoc(sdk.doc(x.firestore(),c,id))).data();});return value;}
const input=(observation,contractor,assignmentId)=>({actor:manager,observation,contractorId:contractor.id,contractor,assignmentId});
test('approved bootstrap initializes existing emulator app and creates assignment',async()=>{assert.equal(initialize().allowed,true);let legacy=0;const out=await callsite.executeManagerAssignmentCallsite({override:callsiteOverride,previewBootstrap:bootstrap,legacyWrite:async()=>legacy++,input:input(base,contractorA,'a-1')});assert.equal(out.allowed,true);assert.equal(legacy,0);assert.equal((await read('observations','obs-a')).currentAssignmentId,'a-1');});
test('approved bootstrap replaces assignment atomically under candidate rules',async()=>{initialize();await callsite.executeManagerAssignmentCallsite({override:callsiteOverride,previewBootstrap:bootstrap,legacyWrite:async()=>assert.fail(),input:input(base,contractorA,'a-1')});const current={id:'obs-a',...await read('observations','obs-a')};const out=await callsite.executeManagerAssignmentCallsite({override:callsiteOverride,previewBootstrap:bootstrap,legacyWrite:async()=>assert.fail(),input:input(current,contractorB,'a-2')});assert.equal(out.allowed,true);assert.equal((await read('assignments','a-1')).status,'REPLACED');assert.equal((await read('assignments','a-2')).version,2);});
test('denied bootstrap never initializes gateway and manager remains on legacy path',async()=>{const denied=bootstrap.initializeAssignmentV2Preview({environment:'preview',explicitOverride:true,featureEnabled:true,hostname:'localhost',projectId:PROJECT_ID,emulatorConnected:false});assert.equal(denied.allowed,false);let legacy=0;const out=await callsite.executeManagerAssignmentCallsite({previewBootstrap:bootstrap,legacyWrite:async()=>{legacy++;return{allowed:true,legacy:true};},input:input(base,contractorA,'a-1')});assert.equal(out.legacy,true);assert.equal(legacy,1);assert.equal(await read('assignments','a-1'),undefined);});
