'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const guard=require('../api/_lib/aiGuard');

class Snap{constructor(value){this.value=value;this.exists=value!==undefined;}data(){return this.value;}}
class Ref{constructor(store,path){this.store=store;this.path=path;}async set(value,options){this.store.set(this.path,options?.merge?{...(this.store.get(this.path)||{}),...value}:value);}}
class Db{constructor(){this.store=new Map();}collection(name){return{doc:id=>new Ref(this.store,`${name}/${id}`)}}async runTransaction(fn){const writes=[];const transaction={get:async ref=>new Snap(this.store.get(ref.path)),set:(ref,value,options)=>writes.push(()=>this.store.set(ref.path,options?.merge?{...(this.store.get(ref.path)||{}),...value}:value)),update:(ref,value)=>writes.push(()=>this.store.set(ref.path,{...(this.store.get(ref.path)||{}),...value}))};const result=await fn(transaction);writes.forEach(write=>write());return result;}}
const input={organizationId:'org-a',uid:'ins-a',observationId:'obs-a',imageReference:'observations/org-a/obs-a/before/a.jpg'};

test('stable operation id is deterministic and tenant isolated',()=>{assert.equal(guard.stableOperationId(input),guard.stableOperationId({...input}));assert.notEqual(guard.stableOperationId(input),guard.stableOperationId({...input,organizationId:'org-b'}));});
test('duplicate/concurrent operation is locked, then completed retry is cached',async()=>{const db=new Db();const first=await guard.acquireAiOperation(db,input,1000);assert.equal(first.allowed,true);const concurrent=await guard.acquireAiOperation(db,input,1001);assert.equal(concurrent.code,'AI_OPERATION_IN_PROGRESS');await guard.completeAiOperation(db,first.operationId,{ok:true},1100);const retry=await guard.acquireAiOperation(db,input,1200);assert.equal(retry.cached,true);assert.deepEqual(retry.response,{ok:true});});
test('expired lock recovers and quota is enforced per uid',async()=>{const db=new Db();const first=await guard.acquireAiOperation(db,input,1000);assert.equal(first.allowed,true);const recovered=await guard.acquireAiOperation(db,input,1000+guard.LOCK_MS+1);assert.equal(recovered.allowed,true);for(let i=2;i<guard.UID_LIMIT;i++)assert.equal((await guard.acquireAiOperation(db,{...input,observationId:`obs-${i}`,imageReference:`key-${i}`},30000)).allowed,true);const denied=await guard.acquireAiOperation(db,{...input,observationId:'overflow',imageReference:'overflow'},30000);assert.equal(denied.code,'AI_RATE_LIMITED');assert.ok(denied.retryAfterSeconds>0);});
test('rate window expiry recovers and another tenant has an independent quota',async()=>{const db=new Db();for(let i=0;i<guard.UID_LIMIT;i++)await guard.acquireAiOperation(db,{...input,observationId:`a-${i}`,imageReference:`a-${i}`},1000);assert.equal((await guard.acquireAiOperation(db,{...input,observationId:'blocked',imageReference:'blocked'},1001)).allowed,false);assert.equal((await guard.acquireAiOperation(db,{...input,observationId:'recovered',imageReference:'recovered'},1000+guard.WINDOW_MS+1)).allowed,true);assert.equal((await guard.acquireAiOperation(db,{...input,organizationId:'org-b',observationId:'b',imageReference:'b'},1001)).allowed,true);});
