'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const dashboard=fs.readFileSync(path.join(__dirname,'..','dashboard.html'),'utf8');
const indexes=JSON.parse(fs.readFileSync(path.join(__dirname,'..','firestore.indexes.json'),'utf8'));
const {evaluateFinalization}=require('../api/storage/finalize')._test;
test('Inspector startup query is tenant/owner scoped, ordered and limited to 25',()=>{const start=dashboard.indexOf('function subscribeObservations()');const end=dashboard.indexOf('window.loadMoreObservations',start);const source=dashboard.slice(start,end);assert.match(source,/where\('organizationId'/);assert.match(source,/where\('createdByUid'/);assert.match(source,/orderBy\('createdAt', 'desc'\)/);assert.match(source,/limit\(OBSERVATIONS_PAGE_SIZE\)/);assert.match(dashboard,/const OBSERVATIONS_PAGE_SIZE = 25/);});
test('older history uses one-shot cursor query, not another realtime listener',()=>{const start=dashboard.indexOf('window.loadMoreObservations');const end=dashboard.indexOf('async function saveObservationToFirestore',start);const source=dashboard.slice(start,end);assert.match(source,/getDocs\(query\(/);assert.match(source,/startAfter\(oldestObservationCursor\)/);assert.doesNotMatch(source,/onSnapshot/);});
test('Firestore index exactly covers tenant owner and descending creation time',()=>{assert.deepEqual(indexes.indexes[0].fields,[{fieldPath:'organizationId',order:'ASCENDING'},{fieldPath:'createdByUid',order:'ASCENDING'},{fieldPath:'createdAt',order:'DESCENDING'}]);});
test('finalization requires exact tenant owner observation and object binding',()=>{const caller={uid:'ins-a',organizationId:'org-a'};const key='observations/org-a/obs-a/before/a.jpg';const upload={ownerUid:'ins-a',organizationId:'org-a',observationId:'obs-a',objectKey:key};const observation={createdByUid:'ins-a',organizationId:'org-a',imageObjectKey:key};assert.equal(evaluateFinalization(upload,observation,caller,'obs-a',key).allowed,true);assert.equal(evaluateFinalization({...upload,ownerUid:'ins-b'},observation,caller,'obs-a',key).allowed,false);assert.equal(evaluateFinalization({...upload,organizationId:'org-b'},observation,caller,'obs-a',key).allowed,false);assert.equal(evaluateFinalization(upload,{...observation,imageObjectKey:'other'},caller,'obs-a',key).allowed,false);});
