'use strict';

const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const state=require('../platform/ai/inspector-human-review-state');
const {resolveInspectorAiPreview}=require('../platform/config/inspector-ai-preview-flag');
const {createLocalPreviewSuggestion}=require('../platform/ai/inspector-human-review-preview-service');
const browser=require('../preview-only/inspector-human-review-preview');
const {MUNICIPAL_INTELLIGENCE_FIXTURES}=require('./fixtures/municipal-intelligence-fixtures');
const dashboard=fs.readFileSync(path.join(__dirname,'..','dashboard.html'),'utf8');

test('preview flag is disabled by default and denies Production hosts',()=>{assert.equal(resolveInspectorAiPreview({hostname:'localhost',localMock:true}).enabled,false);assert.equal(resolveInspectorAiPreview({hostname:'smart-hsr.example',search:'?inspectorAiPreview=1',localMock:true}).enabled,false);assert.equal(browser.resolveFlag({hostname:'smart-hsr.example',search:'?inspectorAiPreview=1'}).enabled,false)});
test('explicit localhost preview activates deterministic local mock only',()=>{assert.equal(resolveInspectorAiPreview({hostname:'localhost',search:'?inspectorAiPreview=1',localMock:true}).enabled,true);assert.equal(browser.resolveFlag({hostname:'127.0.0.1',search:'?inspectorAiPreview=1'}).enabled,true)});
test('manual state is default and never persistent or executable',()=>{const value=state.createHumanReviewState({descriptionDraft:'وصف يدوي'});assert.equal(value.mode,'MANUAL');assert.equal(value.descriptionDraft,'وصف يدوي');assert.equal(value.persisted,false);assert.equal(value.executable,false)});
test('analysis is denied without a valid image',()=>{const value=state.createHumanReviewState();assert.equal(state.beginAnalysis(value,{hasValidImage:false}).code,'IMAGE_REQUIRED')});
test('validated local fixture flows through Municipal Intelligence Engine without network',()=>{const fixture=MUNICIPAL_INTELLIGENCE_FIXTURES[0];const result=createLocalPreviewSuggestion({analysis:fixture.analysis,organizationId:'org-demo',observationId:'obs-local'});assert.equal(result.ok,true);assert.equal(result.networkRequested,false);assert.equal(result.providerCalled,false);assert.equal(result.persisted,false);assert.equal(result.intelligence.provenance.advisoryOnly,true)});
test('suggestion ready leaves category and priority drafts untouched',()=>{let value=state.createHumanReviewState({categoryDraft:'MANUAL_CATEGORY',priorityDraft:'NORMAL'});value=state.beginAnalysis(value,{hasValidImage:true}).state;const fixture=MUNICIPAL_INTELLIGENCE_FIXTURES[0];const service=createLocalPreviewSuggestion({analysis:fixture.analysis,organizationId:'org-demo',observationId:'obs-local'});value=state.receiveSuggestion(value,service).state;assert.equal(value.mode,'SUGGESTION_READY');assert.equal(value.categoryDraft,'MANUAL_CATEGORY');assert.equal(value.priorityDraft,'NORMAL')});
test('existing manual description requires confirmation before replacement',()=>{let value=state.createHumanReviewState({descriptionDraft:'نص يدوي قائم'});value=state.beginAnalysis(value,{hasValidImage:true}).state;const service=createLocalPreviewSuggestion({analysis:MUNICIPAL_INTELLIGENCE_FIXTURES[0].analysis,organizationId:'org-demo',observationId:'obs-local'});value=state.receiveSuggestion(value,service).state;assert.equal(state.useSuggestion(value).code,'DESCRIPTION_REPLACEMENT_CONFIRMATION_REQUIRED');assert.equal(state.useSuggestion(value,{replaceConfirmed:true}).state.provenance.aiSuggestionUsed,true)});
test('Edit marks AI-assisted provenance while Ignore preserves manual text',()=>{let value=state.createHumanReviewState({descriptionDraft:'نص يدوي'});value=state.beginAnalysis(value,{hasValidImage:true}).state;const service=createLocalPreviewSuggestion({analysis:MUNICIPAL_INTELLIGENCE_FIXTURES[0].analysis,organizationId:'org-demo',observationId:'obs-local'});value=state.receiveSuggestion(value,service).state;const edited=state.editSuggestion(value,{replaceConfirmed:true}).state;assert.equal(edited.mode,'EDITING_AI_SUGGESTION');assert.equal(edited.provenance.aiSuggestionEdited,true);const ignored=state.ignoreSuggestion(value).state;assert.equal(ignored.descriptionDraft,'نص يدوي');assert.equal(ignored.provenance.aiSuggestionUsed,false)});
test('Apply updates drafts only and never persists',()=>{const value=state.createHumanReviewState();const applied=state.applyDraftSuggestion(value,'priorityDraft','HIGH').state;assert.equal(applied.priorityDraft,'HIGH');assert.equal(applied.persisted,false);assert.equal(applied.executable,false)});
test('low-confidence secondary is not selected by default and decision stays local',()=>{let value=state.createHumanReviewState();value=state.beginAnalysis(value,{hasValidImage:true}).state;const service=createLocalPreviewSuggestion({analysis:MUNICIPAL_INTELLIGENCE_FIXTURES.find(f=>f.fixtureId==='edge-low-secondary').analysis,organizationId:'org-demo',observationId:'obs-local'});value=state.receiveSuggestion(value,service).state;assert.equal(value.selectedIssues.length,1);assert.equal(value.selectedIssues.includes(value.intelligence.detectedIssues.find(i=>i.confidence<.55).issueId),false);const decided=state.setMultiIssueDecision(value,'MANUAL_REVIEW').state;assert.equal(decided.provenance.multiIssueDecision,'MANUAL_REVIEW');assert.equal(decided.persisted,false)});
test('manual location requires valid coordinates and explicit GPS replacement confirmation',()=>{let value=state.createHumanReviewState();value=state.updateLocationDraft(value,{district:'الوسط',street:'الأول',latitude:'91',longitude:'45'});assert.equal(state.confirmManualLocation(value).code,'MANUAL_COORDINATES_INVALID');value=state.updateLocationDraft(value,{district:'الوسط',street:'الأول',latitude:'24.7',longitude:'46.7'});assert.equal(state.confirmManualLocation(value,{gpsExists:true}).code,'GPS_REPLACEMENT_CONFIRMATION_REQUIRED');assert.equal(state.confirmManualLocation(value,{gpsExists:true,replaceConfirmed:true}).allowed,true)});
test('dashboard contains one compact preview action and manual location control',()=>{assert.equal((dashboard.match(/id="inspectorAiAnalyzeBtn"/g)||[]).length,1);assert.equal((dashboard.match(/id="getLocationBtn"/g)||[]).length,1);assert.equal((dashboard.match(/id="manualAddressBtn"/g)||[]).length,1);assert.match(dashboard,/تحليل ذكي/);assert.match(dashboard,/إدخال يدوي/)});
test('preview integration does not call persistence, assignment, provider, or workflow actions',()=>{const source=fs.readFileSync(path.join(__dirname,'..','preview-only','inspector-human-review-preview.js'),'utf8');for(const forbidden of ['setDoc(','addDoc(','updateDoc(','fetch(','XMLHttpRequest','ASSIGN_CONTRACTOR','UPDATE_STATUS','SAVE_OBSERVATION'])assert.equal(source.includes(forbidden),false);assert.equal(/provider|model/i.test(browser.localFixtureAnalysis({name:'case.jpg'}).shortSummaryAr),false)});
test('dashboard save function remains a separate unchanged call site from Preview analysis',()=>{assert.match(dashboard,/async function saveObservationToFirestore/);assert.match(dashboard,/window\.processSmartInput = async function/);assert.doesNotMatch(dashboard,/inspectorAiAnalyzeBtn[^<]*onclick=/)});
test('browser fixture exposes maximum three rendered issues and low confidence is unselected',()=>{const result=browser.localFixtureAnalysis({name:'multi-low.jpg'});assert.equal(result.multipleIssuesDetected,true);assert.ok(result.detectedIssues.length<=3);assert.deepEqual(result.detectedIssues.filter(i=>i.confidence>=.55).map(i=>i.issueId),[])});
test('no image bytes, prompt, secret, provider or model metadata enters UI state',()=>{const result=browser.localFixtureAnalysis({name:'case.jpg'});const serialized=JSON.stringify(result);for(const field of ['imageBytes','rawPrompt','apiKey','private_key','model'])assert.equal(serialized.includes(field),false);assert.equal(result.provenance.providerHidden,true)});
